import React, { useState } from "react";
import ImageScroller from "./ImageScroller";
import FullScreenModal from "./FullScreenModal";
import { X, Printer } from "lucide-react";
import styles from "../sidebar/SideBar.module.scss";

const MOCK_IMAGE = "https://picsum.photos/800/1600";

const options = [
  "option 1",
  "option 2",
  "option 3",
  "option 4",
  "option 1",
  "option 2",
  "option 3",
  "option 4",
];

const bbcode = `
[page width=640]
[transparent]
[font fontSize=14 fontFamily="DejaVu Serif"]

[[REPRINT_FLAG]]


[area name="logos" offsetY=50]
[/area]

[area name="gameLogo" parentName="logos" x=-90 y=-10]
[center][bitmap base64="iVBORw0KGgoAAAANSUhEUgAAAY0AAADAAQAAAADQbQJ6AAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAACYktHRAAB3YoTpAAAAAd0SU1FB+gLGQkvLTQQRdwAAAjwSURBVGje7dk/b+TGFQDwRzAIUxhiyivOoj+CSwHRiR8lrpL2gDQyImsYHHDX+b6AYX0NF0KWxhWq7K0DGCceFECFDS+FhbNc7GjG78/8Iam9E1mkCGLChmXt/jh8M2/eDEdg514d/Eb+h0ldzCdQzCUNwFzSAeQziQZI5hNQ84hBUswjFkk2nyTziQ9mKqmQlPNJPp9k80k6nyTzCcwiLcRenkgKbqWcQe7kwYoZ5EJIPp1oF342nawlx+aQC0fSycSo2WQrs9IP/xSy8QQmk6WUizlkwXUsDP8EYqzPMfjzRHJvucDS9deJBKOXwQf400Sysm5YAJ5NJNehw+BETSNl6DAoykmk12EyYabNl9qT1WTiOgzyzVTiMgzJbirRgdxPJV0g08JfxA6bSsqQYUQWEx+snk98H0uJeZRQH0Ekq0mt7PywqImt7OyN9hVpIrH2Reen/WSSda6CmanjYrLWlfzJpMsbt0j+t4jBqNu8nkEa6qKm8EQ/TmQJbooqkOLDs3JlZNGqyyoN5OYDxECm5aeqhEjevZ9QFLgSfTsiZbOfUMw1RnGnedDhJO53ynovaYtOUVG1NzV/F84jUXSrhwTbeI3k3l5V1J5B4jZiLZJyD9F4nxt7gSO+5PLQIw1gYHsI9Ym2X2EYX3MN1nDmSY2kGJM6s1cGEqOIHPMk8QSjwyEdE0NxFliBygsk5pRHvwONBIeEP6ZH7ZOGbqqo9iy/gUS3vGgTyek2luiYLPHfLU307BZJJ+8sLWi34+uIZA/Jmoppsj6C9K7hkWyhc7sEnJymR2r63bUGe8WVcYvEjaQjCfVxwdEyMRRcYd+iu+DKeIZERhK/2LmSVEOpA6HMsVf2ByQnsvKeQvpaCr0jGZVZFQlfWyLmTNbE55DKSHqS04zDbyeB4LQ26gfsWYk1byG7xMY4yk7WYhziPqFuUiWO31ZWHyxdVPBUJCV+M8XveSL3ubiEZNcEIiPpicKvZ7YZkmyJZC2rT8okiYT7OJexiCShIb+V1SfFidzIzKrhzPdxQWtTn8AaydItPXhLGUn81pnv48JCIBLz59/wYHCPIZGRdIT7ODdj8qzjwcB5hJUEcrdkC6E+hly79AzkGIf8kh4bJ2wDB25fVMExSOpzJw7JIRJN9+6SbQMfuf2qEBV2GANygFmCHxSVzt7V8AeAL4SccAT6PYSaPlcn+Xc1PAHYCTmUda8ekCYkFpKtfVuWNfgdPlBUabjvkEiWJBus+Z/X4N8jmGQ2PNkDgkm0tJvtrva7DyS/dz+OSG55yClLLux6s6t6rXhdjUntsiRb2N1S3m+vh6TukxpJ44my9wtuJVkFktrw+JG88eRA+Re8MWmH5LBrKeMxFw/o0w0/92ZIuiEpDHcXksOp5GODQ18T+ZgJf/r3IdHjVpgUjthHSSUPNibPwmikUriGRDd9cjsiSVs8IOVWCAhZyQSKY045OiY3HPv7CX51RI5yJiWTW/szflZBrnqkdAG6ckG/gEjeEElGpHhADM1gR/5Fz5ByhsbNez4mquuRfyok2YhkY8KFh8lTa1X5lqsfZ/97CQfI/xxao17jQBf7STIguOIrzGSl17e4nh23kv37iX//B/gbdlO5frdGcvRcSPMBktwyyV69qvVXmJOnkv0fIumKSdqU1Qn2Bu4W9pG0T7LvkdR0GyiOsc1Lyf42jIt5QPIvAe4wWNpB48q77JE/PiAyd0os1/dIypaqeXr9tWQ/kVNwKwz4PYwQjb+6lydPkFy8FUIzXnNaPiDpFmP5yQWLZPG9ZD+97xhOeu1SLZD8Bj8wLlhcnBYrIZqeH8IK0ydqif/BosEXhrPAYaLspwXPckeOSW5x55SsTiPZyIShWcE7C7cHEcK7lQ43Sok9kvDxK+W64uw3Erkak5S207TFv5REILJzEyYc17ZuPnuiCyI0GCCLk9rWkv3hIL0ZkhbDw13PtWxIaNVUOEYlEf+OJEQF8sJKY7LtOcGipvSdHPT4dySZOVZI6yt7atf8+zMidP7Cc8y3Ug0Ix0lZwrs+2lUfKDrhy/rETZcRWWjejP+7KbANnNWKQ7A2VPE0ktIRQ1v+4js+FnKreOs6WY+IfEYvFhiMesYHou7qwmmtJDKTxhN8Psy0TH+BP/dIEUcyj0RZ1xj2LL3qhb82hNdc6eMikNwRxa9iV11m42XcNoP7uLgPxHqC/apLO7j8kYLLF0cOKMvb1Cpr2/hXE7oN317FJXwXiN1/JT/KShoKrXWt1PEvOMPLJC2+cPCGuXduOyCV6oNKmeROerd0RTON5LA/ANJARiT9BdMgnI7RSF47wo3ofti2S21lTbqyvTO4wfnY/TAG7GZH/mN7J300kmo/oXcK7HGszvTs1/HgCldhTwbP1CX0YhPJMh6PAc87CX/QBBLc9Cee3MZDuMS6E8V+RjX0VEOyjqeDqX14bgn0GpLSIlMHsu2fQY7PYZpS1m5HEqt5Fx67rODX6Ei6pD6RHUJdVlS9HMF+9fEr+rtCJJjBRDIMggkgkSgXfolNiO8hdckkAePJtQ8m47PlSLBz63PaICFRlU2rQFYUzCccyn0gbzxJOibniemRdeygdSAvJEuq81QTwf2CySLpZdMqkFdMlCMXuHzprDr3xMRZdN0nZYOvs0xoK5fqHP/HdjL1FoGoSMxR3uADnaVaNstJ1yfLMClsIC+ffupI5wmuGDgDfsf9uRlEL2n58uknq5pJS5vlSuGSDMd0IjCcTStP2vTlk8/oGKvSvCfFUWEC8KlbJ338i0ASJDn1lKY9KaaUhWZAlv1QmHz70dHznGKg8o0ExmTdD4XIOySKCO2IqJaBgbpsesSNzOsB+QsT2mZUONGapFbNUyIuCP6yVn0CnxVMsqokgulmiYRh76zLRE9eIMEXaYsE857OE9LKNk/6ZQfzoysjabID4HrMBIhk/7Bt2RNYttrc9kheWCZJIMWg2I4uIny/SA77K+V+ImExyYXkdiIxjhTWTiS0ZuV14f9YPpk0jzVhexUGmDwORmQKGJCpVyATm7DjxeI38n9GfgUSSqE1GXawywAAACF0RVh0YXV0by10aHJlc2hvbGQ6dGhyZXNob2xkADc0LjUwOTgl1iSFUwAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyNC0xMS0yNVQwOTo0Nzo0NSswMDowME8/QHMAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjQtMTEtMjVUMDk6NDc6NDUrMDA6MDA+YvjPAAAAKHRFWHRkYXRlOnRpbWVzdGFtcAAyMDI0LTExLTI1VDA5OjQ3OjQ1KzAwOjAwaXfZEAAAAABJRU5ErkJggg=="][/bitmap][/center]
[/area]

[area name="Logo" parentName="logos" x=195]
[center][bitmap base64="Qk34WwAAAAAAADYEAAAoAAAAnAAAAJAAAAABAAgAAAAAAMJXAAASCwAAEgsAAAAAAAAAAAAA////AOzs7ADq6uoAb29vAPDw8ACZmZkAHx8fAHh4eAAbGxsAGRkZAL29vQAAAAAAIyMjAPn5+QCenp4AHR0dAPT09ADe3t4AtbW1AH9/fwAhISEAAgICACAgIAD29vYAx8fHAKWlpQBaWloANDQ0ABgYGAAyMjIA4+PjAMvLywBAQEAAjo6OAP39/QD6+voA7+/vANvb2wDV1dUA0dHRAMXFxQC4uLgAoaGhAIGBgQBxcXEAYmJiAExMTAAsLCwAExMTAJWVlQDT09MAurq6AKCgoACqqqoAmpqaAIaGhgB2dnYAXl5eAEVFRQA5OTkAMTExACsrKwAnJycADg4OAAkJCQADAwMAFRUVALu7uwDc3NwAxsbGAGNjYwBVVVUAMDAwABwcHABHR0cA8fHxAPPz8wDKysoAwMDAANjY2AD4+PgA2dnZAM3NzQCoqKgAe3t7ACYmJgANDQ0ACgoKABEREQAWFhYArKysAPf39wDn5+cAbm5uAEJCQgAvLy8ACwsLAGhoaAB+fn4Ah4eHAJGRkQCkpKQAnJycAISEhAA+Pj4ABgYGAN3d3QA1NTUAgICAAKurqwBlZWUAU1NTAAwMDAB0dHQAo6OjANDQ0ACLi4sAXFxcAGBgYAAQEBAAUlJSAPz8/ACMjIwASkpKAKenpwAFBQUAtLS0AOnp6QDg4OAAw8PDAIiIiAA/Pz8ANjY2AHx8fABpaWkAKSkpADo6OgDm5uYA8vLyAF9fXwAHBwcAlJSUANbW1gC/v78AUFBQAN/f3wDIyMgAtra2AGtrawB5eXkArq6uAKKiogBISEgAFxcXAJCQkABwcHAAt7e3AB4eHgDU1NQAsLCwAHJycgBmZmYAk5OTACQkJACXl5cAr6+vAEFBQQCdnZ0AbW1tAGdnZwCSkpIAiYmJADc3NwDh4eEAKioqALm5uQDo6OgAGhoaAF1dXQDr6+sAm5ubAERERABXV1cAfX19AMLCwgBbW1sAPDw8AHNzcwAEBAQAhYWFALOzswDi4uIAsbGxAGpqagBGRkYAOzs7AAEBAQDl5eUA7u7uAFhYWAAtLS0Ara2tAM7OzgBkZGQAj4+PAJaWlgBJSUkAzMzMAE1NTQC+vr4AVlZWAHV1dQD+/v4A19fXABQUFAAICAgAYWFhAE5OTgCCgoIAKCgoAKampgDExMQAEhISAHp6egB3d3cA5OTkAJ+fnwBRUVEAS0tLAPv7+wD19fUAycnJAI2NjQDBwcEAWVlZADMzMwAuLi4AsrKyAE9PTwBDQ0MAODg4AD09PQBUVFQA0tLSAIODgwDt7e0AqampAA8PDwBsbGwAIiIiANra2gAlJSUAz8/PAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADQEBDQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANRQSyVFwDU1DmdnpzU1KY9P4UsXAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMlpxSjxJjAsLCwsLCwsLP0LsiEo5NWoNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI1FGCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsPqykjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABcmgwkLCwsLCwsLC0IcVT09PRRCjAsLCwsLCwsLC1YdMU1MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf109CwsLCwtpXotnNo+4cyYmJh+PbY1hkKNACwsLCwsLjBbOZCQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABLBzALCwsLSe5kRVEBWwAAAAAAAAAAeRAR85NmXUkLCwsLCwsLnRoKFwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH8aCwsL1/uaAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIWFfQAsLCwtph6VRAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATMwLCwsLSmbGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeSQ1YexACwsLC0k5gSIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANllgLCwvurQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANUOLgsLCwsLCcEyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFXgsLCw9KICAgPTugbGwqMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKVJfQsLCwsd8yMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADU5lxFM2cvCwsLCwsLCwsLQBR7OHxFagAAAAAAAAAAAEyPDpRG79BHp5+SHlsiAACRZS9WCwsLCYYBDQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATE5yufFJd2kLCwsLCwsLCwsLKx9cIwAAAAAAAAAAAAAAAAAiF0QmGXUdQFadO4aliQAAAI6kCQsLC33HNRcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAERnaAsLCwsLCwsLCwsLCwsLCxSlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXBT0LCwsLmdoCAAAirdkLCwsLQsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI6nYRYLCwsLCwsLfQaskKhsfoABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABSwR1ACwtVLCcjABcsSX0LC3BTFwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB5fx4eHgEAAAAAAAAAABefYS9AFQsLCwsLCz27p0WtECIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAExRKWxkc7AjIkTc7mkLQT6LkgBMbbULCwtwYxcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATCmokEpKSkegChcAAAAAc6vsQAsLCwsLCwsLC0JoqSEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0BRMnMe9m3c0wNJ9hBCwuMIBkAik5wCwsLPo8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXEXN+ISzHRztVSsmNSAsLCwsLCwsLfWgqjn6UCwsLCwsLCwsLCwsLCwsLCwtnDQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF4FuPaOGNiUndAkLCwuUMluBe30LCzBzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1OZL51qkYS5VCwsLCwsLCxYJCwsLfVc/YBULCwsPx/BpCwsLFVkwQQsLCwsLCwsLCwtKjgAAAAAAAAAAF0wiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABNUYPCS0K4VSuQAtXuUMN6cgLCwthSwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAycrlKBhULCwsLCwsLCwsLCwsLC0BuqxkpU5XkcAsLCwsLCwsJ2E7HQAsLCwsLCwsLCws9NQAAAAAAAHlNi28hRYkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAExDZ3BZiJacywsLCxQyIukPCwsLlYoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4/CwsLCwsLCwsLCz9KIZoGCwsL5EQAAAAAAAA5x0LCwsLCwtVAgBhQJQ9CwsLCwsLCws9NQAAAAAAAI9CCwsLCxzLGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHJCC33OgNkLCws7CgBFCwsLQo8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAS3ULCwtCVbpvjWXnHgAAAB8UC/DMiQAAAAAAAAAAAEykHAsLCwtwGQBUMFEAAAFzNWwLCws7RQAAAAAAiqRpCwsLCwsLCx1vwAAAAAAAAAAAAAAAAAAAAAAAAAAAAACRZRRBh3SUVX0LPScAZFYLC0pFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAksMLVy2Tc4lLAAAAAAAAAI9CC74jAAAAAAAAAAAAAAAAq2kLCwsL8A3Td4AAAAAAAEULCwsbCgAAAAAAJHQWAAAAAAAAoAsLCzCAADVYG1gLCwsLCwsLC8RXIJVPeQAAAAAAAAAAAAAisHELC1cxMjsLCwxSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAuIQLBucAAAAA5/ELC1kLC6AAAAAAAAA7CwsLCws0AAAAAAAACwsLC319C38AAAAAAMALCwvIpQAAAAAAEI1ZAAAAAAAAoAsLC7F/ADX7GQ5JCwsLCwsLCwsLC97ZEwAAAAAAAAAAAAAAIk89CwsMpM4LC1lOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKR0LSUUAAAAAAAAXHspDKbKYygAAAAAjpWsLDEUAAAAAADJeCwsLCzagPx4AAAAAAI8LCwsdKQAAAAAASyELCwsLCwsLCwsLC14AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFtEXQt9SXALCwkZIhkLCwt3cwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKR0LSUUAAAAAAAAXHspDKbKYygAAAAAjpWsLDEUAAAAAADJeCwsLCzagPx4AAAAAAI8LCwsdKQAAAAAASyEJRl5ZfQsLCwsLC50kAAC/BSwZklsAAAAAAAAAAAAAAAAAAAAAABkbfQsLCwuZjgBUCwsLoFsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAChsLnZIAAAAAS0WkLEoUD3CiigAAAAD6O0ELFbsAAAAAAExUCwsLCyFdVokAAAAAACkLCwtffgAAAAAATGQvF1Irzl9YvAsLC5mJACNsWEFZmDZEDQAAAAAAAAAAAAAAAAAAAABlG4wLCwsLVA1FMAsLXjIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARTsLFB8AAAAAH14LCwsLC/v8AAAAAACVvAsLC3cAAAAAAAAyCwsLC2JuQAEAAAAAADULCws9NQAAAAAAF6QwAAAAAlESwgsLC0kBACZXCwsLCwsdXb6JAAAAAAAAAAAAAAAAAAAAytILCwsLVXMAYUELCHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANT0LHLgAAAAAJkcLCwsLC0pLAAAAAACLCwsLCwtsAAAAAAABCwsLCzmgMFEAAAAAACYLCws7RQAAAAAAAWdVAAAAAAAAoAsLCz9RADULCwsLCwsLCwsPwCMAAAAAAAAAAAAAAAAAAAA9CwsLjDEACjALC0cAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANT0LHLgAAAAAJkcLCwkLC2F5AAAAAAA6CwsLCws4AAAAAAAACwsLC2IHMFEAAAAAACYLCws7RQAAAAAAAWdVAAAAAAAAoAsLCz9RADULCwsLCwsLCwsLdyC0AgAAAAAAAAAAAAAAAADK2HALC85QyqMLCyACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfl8LCCgAAAAAcy4LCxYLC6AAAAAAAAA7CwsLCwtGAAAAAAAACwsLCzvraYAAAAAAAEULCwsbCgAAAAAAJHQWAAAAAAAAoAsLCzCAADVYG1gLCwsLCwsLC8RXIJVPeQAAAAAAAAAAAAAisHELC1cxMjsLCwxSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAuIQLBucAAAAA5/ELC1kLC6AAAAAAAAA7CwsLCws0AAAAAAAACwsLC319C38AAAAAAMALCwvIpQAAAAAAEI1ZAAAAAAAAoAsLC7F/ADX7GQ5JCwsLCwsLCwsLC97ZEwAAAAAAAAAAAAAAIk89CwsMpM4LC1lOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKR0LSUUAAAAAUkoLC0pAC0cXAAAAAACgvAsLC3cAAAAAAABqCwsLCwsLCx4AAAAAAI8LCwsJ0jEpcxcASyEPAAAAAAAAoAsLC0IeADUdRAANjlQ7VgsLCwsLCwsLC4hmjgAAAAAAAAAAAAAXdYwLd3cLCz8pAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGDsLHLgAAAAAH14LC7l3C6azAAAAAACc1gsLFc4AACSn6ssLCwxZGTJQ7iSHhcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIlnV3BnigBRi1iMVo0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjo8FeAkLCwsVV1k9kDmNM0WRAAAAAABMHpKTYpSDDwsLCwsLQUA/QlUgb0eVMZZml2ZnYZiHCwsLCwtXPx1KditiB1VwCwsLCwsLmYKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHlNVQsUegohFgsLeyUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIQc3wrGzALCwsLC30GHTt4ZyF+H0sAAAAAf4CBNYJdgzALCwsLCwsLCwswDIQ7eCxnhThUgoY9CwsLCwsLV4eIdhorSQsLCwsLCxZkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMjtWCwsLFWtsTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABcybW5vHUlWCwsLCwsLC3BVLzs7RnEOcikpKXMfTnQDA3VeVUlCVwsLCwsLCwsLWVU7RnYaOwwcMAsLCwt3R3hCPwsLCwswTXkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApGFlhZPFoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFtcKSFdXl8MWEALCwsLCwsLCxVgPw8PDy5hYmNkZWZnLl5oVTBAQEELCwsLCwsLC0FZDxtfVT8LCwsLC2k9SQsLCwsLGmoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMTUNOT1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVFSKVMhIVRKVVYLCwsLCwsLCwsLCwsLCwsLC1dCMDBAQEELCwsLCwsLCwsLCwsLCz8LCwsLCwsLCwsLCwsLWCwNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAREU1RkdIPT1JQkALCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLC0pLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHjIzNDU2ISE3OAM5OjsbPD09PhQIP0BBCwsLCwsLCwsLCwsLCwsLCwsLC0JDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiIw0XJB4RJSYmJx8oKSorLC0uLzALCwsLCwsLCwsLCwsLCxUxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFx4fGSALCwsLCwsLCwsLCwshAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXGBkaGxwLCwsLCwsdAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQERITFBULCwsWAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0CDgwLCwsPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKCQsMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwgJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAUGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"][/bitmap][/center]
[/area]

[area name="message" offsetY=50]
[center]
[font fontSize=24 fontFamily="DejaVu Serif"]
[b]PILOT - VOID NOT FOR SALE[/b]
[/font]
[/center]
[/area]

[font fontSize=18 fontFamily="DejaVu Serif"]
[area name="printDate" offsetY=-35]
[center]Tue. Jun 3, 2025 16:14:02[/center]
[/area]

[area name="serial-number" offsetY=5]
[center]113738-000014 6 TR:10171437[/center]
[/area]

[area]
[bitmap base64="PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NDAiIGhlaWdodD0iNyI+PGxpbmUgeDE9IjAiIHkxPSIwIiB4Mj0iNjQwIiB5Mj0iMCIgc3Ryb2tlPSIjMDAwMDAwIiBzdHJva2Utd2lkdGg9IjMiIC8+PGxpbmUgeDE9IjAiIHkxPSI1IiB4Mj0iNjQwIiB5Mj0iNSIgc3Ryb2tlPSIjMDAwMDAwIiBzdHJva2Utd2lkdGg9IjMiIC8+PC9zdmc+"][/bitmap]
[/area]


[area name="header" offsetY=10]
[/area]
[area x=-150 parentName="header"]
[center]
[u][b]Your Numbers[/b][/u]
[/center]
[/area]

[area offsetY=5]
[area name="A."][/area]
[area parentName="A." x=15]
[b][font fontFamily="DejaVu Serif" fontSize=24]A.[/b]
[/area]

[area parentName="A." x=90] 
651   STR    
[/area]

[area parentName="A." x=400] 
 1.00 QP
[/area]

[/area]


[font fontSize=default fontFamily="DejaVu Serif"]
[area offsetY=5]
[bitmap base64="PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NDAiIGhlaWdodD0iNyI+PGxpbmUgeDE9IjAiIHkxPSIwIiB4Mj0iNjQwIiB5Mj0iMCIgc3Ryb2tlPSIjMDAwMDAwIiBzdHJva2Utd2lkdGg9IjMiIC8+PGxpbmUgeDE9IjAiIHkxPSI1IiB4Mj0iNjQwIiB5Mj0iNSIgc3Ryb2tlPSIjMDAwMDAwIiBzdHJva2Utd2lkdGg9IjMiIC8+PC9zdmc+"][/bitmap]
[/area]

[area name="options" offsetY=10]
[font fontSize=18 fontFamily="DejaVu Serif"]
[center][size height=2][b]plus FIREBALL - NO[/b][/size][/center]
[/font]
[/area]


[area name="noOfDraws" offsetY=-10]
[font fontSize=18 fontFamily="DejaVu Serif"]
[center][b]Good Luck With Your 2 Draw(s)[/b][/center]
[/font]
[/area]

[area name="drawDate" offsetY=-20]
[font fontSize=18 fontFamily="DejaVu Serif"]
[center][b]06/03/2025 - 06/04/2025[/b][/center]
[/font]
[/area]

[area name="drawPeriod" offsetY=-20]
[font fontSize=18 fontFamily="DejaVu Serif"]
[center][b]BOTH DRAWS[/b][/center]
[/font]
[/area]


[font fontSize=12 fontFamily="DejaVu Serif"]
[area name="total_cost" offsetY=-20]
[center][size height=4 width=2][b]Total: $2.00[/b][/size][/center]
[/area]
[/font]


[font fontSize=16 fontFamily="DejaVu Serif"][area offsetY=30]
[center][size width=1]Want more chances to win?[/size][/center]
[/area]

[area]
[center][size width=1]Try our Fast Play games[/size][/center]
[/area]

[area]
[center][size width=1]10X Lucky, Ultimate Diamond[/size][/center]
[/area]

[area]
[center][size width=1]Jackpot, Blackjack[/size][/center]
[/area]

[area]
[center][size width=1]And $100K Crossword[/size][/center]
[/area]

[area]
[center][size width=1]Blowout.[/size][/center]
[/area]

[area]
[center][size width=1]Play Today![/size][/center]
[/area]
[font]

[area name="jackpots" offsetY=30 ]
[/area]

[area parentName="jackpots" name="leftContainer" y=0 x=210]
[b]LOTTO[/b]
[/area]

[area parentName="jackpots" name="rightContainer" y=0 x=330]
[b]$0.00[/b]
[/area]
[area parentName="jackpots" name="leftContainer" y=30 x=210]
[b]LDL[/b]
[/area]

[area parentName="jackpots" name="rightContainer" y=30 x=330]
[b]$0.00[/b]
[/area]
[area parentName="jackpots" name="leftContainer" y=60 x=210]
[b]POWER[/b]
[/area]

[area parentName="jackpots" name="rightContainer" y=60 x=330]
[b]$0.00[/b]
[/area]
[area parentName="jackpots" name="leftContainer" y=90 x=210]
[b]MEGA[/b]
[/area]

[area parentName="jackpots" name="rightContainer" y=90 x=330]
[b]$0.00[/b]
[/area]




[area offsetY=20 name="bonusPlay"][/area]

[b]
[area parentName="bonusPlay"]
[center]
[font fontSize=17 fontFamily="DejaVu Serif"]
[area offsetY=30]
[center][size width=1]Be Smart, Play Smart®[/size][/center]
[/area]

[area]
[center][size width=1]Must be 18 or older to play.[/size][/center]
[/area]

[/b]
[/font]
[/center]
[/area]
[b]


[area offsetY=30 name="serialNumbers"]
[font fontFamily="DejaVu Serif"]
[center]
[font fontSize=16 fontFamily="DejaVu Serif"]
[b][center]00026 47552 02181 03808 03367 00823 00000[/center][/b]
[center]30411 87451 21703 56802[/center]
[/font]
[/center]
[/area]

[[REPRINT_FLAG_FOOTER]]

[area offsetY=5 name=barcode]
[center][barcode format=graphics elementSize=1 type=PDF417 value="0002647552021810380803367008230000030411874512170356802" scale="3"][/barcode][/center]
[/area]

[area offsetY=30]
[/area]

[/page]

`;

export const hugeHtml = `
<article style="background:#fff;padding:2rem;color:#111;">
  <h1 style="margin-top:0">2025 Annual Sustainability Report</h1>
  <p><em>Scroll ↓ to read the full document</em></p>
  ${
    "<h2>Executive Summary</h2><p>" +
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ".repeat(25) +
    "</p>".repeat(1)
  }
  <img src="https://picsum.photos/id/1015/800/400" />
  <h2>Key Metrics</h2>
  <ul>
    <li>CO₂e reduced: <strong>-18 %</strong></li>
    <li>Renewable energy share: <strong>62 %</strong></li>
    <li>Water usage: <strong>-9 %</strong> YoY</li>
  </ul>
  ${
    "<h2>Section</h2><p>" +
    "Proin tempus semper purus, vitae scelerisque ex fermentum sed. ".repeat(
      30
    ) +
    "</p>".repeat(1)
  }
  <img src="https://picsum.photos/id/1024/800/400" />
  <h2>Appendix</h2>
  ${
    "<p>" +
    "Curabitur dignissim, metus at ornare semper, turpis lacus hendrerit nunc, ".repeat(
      120
    ) +
    "</p>".repeat(1)
  }
</article>
`;

export default function ReportRendered({
  onClose,
  onPrint,
}: {
  onClose?: () => void;
  onPrint?: () => void;
}) {
  const [open, setOpen] = useState(false);
  const renderMainAreaButtons = () => {
    return options.map((option) => {
      return (
        <button
          className={styles.labelItem}
          style={{ marginBottom: 24 }}
          onClick={() => {}}
        >
          {option}
        </button>
      );
    });
  };
  return (
    <div>
      <div style={{ display: "flex", flexDirection: "row", gap: 12 }}>
        {renderMainAreaButtons()}
      </div>
      <button onClick={() => setOpen(true)}>Open</button>
      <FullScreenModal open={open} onClose={onClose}>
        <div
          style={{
            height: "100%",
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          {/* Sidebar-style label button */}
          <button
            className={styles.labelItem}
            style={{ width: 200, marginBottom: 24 }}
            onClick={() => {}}
          >
            Sidebar Style
          </button>
          <div style={{ padding: "2rem" }}>
            <ImageScroller
              src={bbcode}
              // templateData={{ user: "Maria", coins: 172 }}
              /* stretch horizontally */
              fill={true}
              sourceType="html"
              className="full-width-scroller"
            />
          </div>
          <div
            style={{
              flex: "0 0 10%",
              width: "100%",
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
              padding: "0 2rem",
            }}
          >
            <button
              style={{
                background: "red",
                color: "#fff",
                border: "none",
                borderRadius: 6,
                padding: "12px 32px",
                fontWeight: 600,
                fontSize: 18,
                cursor: "pointer",
                display: "flex",
                flexDirection: "column",
                alignItems: "center",
                justifyContent: "center",
              }}
              onClick={onClose || (() => setOpen(false))}
            >
              <X size={28} style={{ marginBottom: 4 }} />
              Close
            </button>
            <button
              style={{
                background: "#2563eb",
                color: "#fff",
                border: "none",
                borderRadius: 6,
                padding: "12px 32px",
                fontWeight: 600,
                fontSize: 18,
                cursor: "pointer",
                display: "flex",
                flexDirection: "column",
                alignItems: "center",
                justifyContent: "center",
              }}
              onClick={onPrint || (() => alert("Print"))}
            >
              <Printer size={28} style={{ marginBottom: 4 }} />
              Print
            </button>
          </div>
        </div>
      </FullScreenModal>
    </div>
  );
}
